# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 19:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('Type', models.CharField(choices=[('Null', 'Null'), ('Phone', 'Phone'), ('Car', 'Car'), ('Laptop', 'Laptop'), ('jops', 'Jops'), ('Electronic', 'Electronic'), ('Clothes', 'Clothes'), ('Makeup', 'Makeup'), ('Furnishings', 'Furnishings'), ('books', 'books'), ('sports', 'sports'), ('Property', 'Property'), ('Other', 'Other')], default='Null', max_length=120)),
                ('company', models.CharField(max_length=120)),
                ('dis', models.TextField(default='in here you w,ll write all the discribtion about your product')),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('case', models.CharField(choices=[('Null', 'Null'), ('New', 'New'), ('Old', 'Old'), ('Second Hand', 'Second Hand'), ('Other', 'Other')], default=99, max_length=120)),
                ('price', models.BigIntegerField(default=0)),
                ('address', models.CharField(max_length=120)),
                ('draft', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('puplis', models.DateTimeField(auto_now_add=True)),
                ('auth', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-puplis'],
            },
        ),
    ]
