# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 10:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170104_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='auth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
