# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 16:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170106_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(choices=[('Null', 'Null'), ('Kosti', 'Kosti'), ('Khartoum', 'Khartoum'), ('Rabbik', 'Rabbik'), ('Duwaim', 'Duwaim'), ('Sinnar', 'Sinnar'), ('Bahri', 'Bahri'), ('Omdurman', 'Omdurman'), ('Sawakin', 'Sawakin'), ('Port Sudan', 'Port Sudan'), ('Kasala', 'Kasala'), ('Madani', 'Madani'), ('Alabid', 'Alabid')], default='Null', max_length=120),
        ),
        migrations.AlterField(
            model_name='post',
            name='auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
