# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-04 10:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='parent',
        ),
        migrations.AlterField(
            model_name='post',
            name='auth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
