# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20170313_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='auth',
        ),
    ]
