# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 16:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20170313_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Post',
            name='auth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
